
gui:
  # Use a nerd font for icons
  nerdFonts: true
  # Use rounded borders for a softer look
  border: 'rounded'
  # Set a custom theme
  theme:
    activeBorderColor:
      - '#88C0D0' # Frost Blue for active panel
      - bold
    inactiveBorderColor:
      - '#4C566A' # Dark Grey for inactive panels
    selectedLineBgColor:
      - '#434C5E' # Slightly darker background for selected lines
    optionsTextColor:
      - '#81A1C1'
    cherryPickedCommitBgColor:
      - '#4C566A'
    cherryPickedCommitFgColor:
      - '#EBCB8B'
    unstagedChangesColor:
      - '#BF616A' # Red for unstaged changes

